permalink: /:categories/:year/:month/:title/
relative_permalinks: false
markdown: redcarpet
baseurl: /melvinchien.github.io
exclude: [".gitignore", "CNAME", "Gruntfile.js", "LICENSE", "LICENSES.md", "node_modules", "package.json", "README.md", "start.sh", "validation-report.json", "validation-status.json"]
